### ISSUE TITLE
Highlighted bold/italics text: spurious spaces in Live Preview

### ISSUE THREAD

**Issue by lebigot** [colineckert/obsidian-things#111]
Hello,

In Live Preview, bolded and italicized words are displayed with spurious spaces on each side.

Example: `==There are spurious spaces around **bolded and italicized words**: _look_!==`

<img width="550" alt="Screenshot 2022-12-29 at 22 01 52" src="https://user-images.githubusercontent.com/5793/210010747-d8561420-24c6-4008-9f67-7f4df76a80a7.png">

This can be troubling, because it looks like the source has spurious spaces.

The default theme displays this correctly.

PS: another problem is that in Live Preview, the markdown marks (`**` and `_`) are not visible, in dark mode, in highlighted text:

<img width="550" alt="Screenshot 2022-12-29 at 22 05 49" src="https://user-images.githubusercontent.com/5793/210011059-f2977759-6f9d-420d-b8bc-4bbc4f53c47a.png">

Should I open another issue?

Thanks!

**Comment by colineckert** [comment]
Hi @lebigot, thanks for creating this issue. This spacing bug with nested formatting was introduced by a recent change to add padding for highlights. Agree that it doesn't look great. I'll revert. 

The markdown marks are dimmed to add focus on the styled text rather than the marks themselves. in highlights, this can be hard to see. I'll try to improve this experience.

**Comment by colineckert** [comment]
hey @lebigot, I just pushed an update to address these issues. Pls update your theme and if all looks good, pls close this issue. thanks!

**Comment by lebigot** [comment]
Perfect! Thank you so much for the fast turnaround and the great final result!
