### ISSUE TITLE
[Bug] Multicolor highlights all display as yellow-colored

### ISSUE THREAD

**Issue by ParkerRobb** [colineckert/obsidian-things#146]
Previously I was able to highlight text with different colors using the [Highlightr](https://github.com/chetachiezikeuzor/Highlightr-Plugin) plugin, which wraps text in an html `mark` tag:

```html
<mark style="background: #ADCCFFA6;">text</mark>
```

The most recent update of this theme ignores the color specified by those tags and displays all of them in the default yellow color.

The default Obsidian theme respects the specified colors.

**Comment by colineckert** [comment]
hey @ParkerRobb thanks for flagging this issue! i just released a new version making the "fancy" yello highlight styles optional via a style settings plugin toggle. Update your version to 2.1.14 and if the issue is resolved pls close this issue. thanks! https://github.com/colineckert/obsidian-things/releases/tag/2.1.14

**Comment by ParkerRobb** [comment]
Looks like it works as before. Thanks!
