### ISSUE TITLE
Missing Floating Action Button on Mobile

### ISSUE THREAD

**Issue by ianlhayes** [colineckert/obsidian-things#51]
I love your theme! One thing I really enjoyed when I first installed it was the Floating Action Button—it made it super quick and easy to tell which mode I was in and to switch between editing/reading modes (something that has gotten increasingly more relevant as Obsidian has moved toward Live Preview).

Sometime in the past few weeks, after switching between themes, I noticed that the Things theme for mobile no longer presents a floating action button. I have the Style Settings plugin installed, so I thought that might have been interfering, but when I loaded a known-good test vault with no plugins enabled, I had the same issue. Is there something I'm doing wrong, or a better way to reinstall the theme than deleting and reinstalling it from the community themes browser? I know its a minor thing, but the Floating Action Button is a core differentiating feature of this theme and I absolutely love it!

For reference, my Obsidian version is Obsidian Mobile 1.2.0 and I'm testing with Obsidian Things theme version 1.6.8

**Comment by colineckert** [comment]
Thanks for raising the issue! Nothing you're doing wrong, this was a bug introduced by a change in the CSS selectors from an Obsidian mobile update. 

I debated whether it was still useful now with Live Preview on mobile, but it seems you and others really like the FAB (yay!) and so it has been brought back in the latest Things version. Just update your theme and you should see it again! 

Let me know if the issue is not resolved. Thanks again!
